-- Onboarding tour i18n labels (8 languages)
-- Category: tour

INSERT INTO datapai.sys_lang_labels (label_key, lang, text, category) VALUES
-- English
('tour_step_label', 'en', 'Step', 'tour'),
('tour_skip', 'en', 'Skip tour', 'tour'),
('tour_back', 'en', 'Back', 'tour'),
('tour_next', 'en', 'Next', 'tour'),
('tour_finish', 'en', 'Got it!', 'tour'),
('tour_search_title', 'en', 'Search any stock', 'tour'),
('tour_search_desc', 'en', 'Type a ticker or company name to jump straight to its analysis page. Works across all 9 markets.', 'tour'),
('tour_watchlist_title', 'en', 'Add to your watchlist', 'tour'),
('tour_watchlist_desc', 'en', 'Click the star on any stock card to track it. Your watchlist syncs across devices and feeds the AI copilot.', 'tour'),
('tour_nav_watchlist_title', 'en', 'Your watchlist', 'tour'),
('tour_nav_watchlist_desc', 'en', 'All your starred stocks in one place. See prices, changes, and AI alerts at a glance.', 'tour'),
('tour_nav_ai_title', 'en', 'AI Analysis', 'tour'),
('tour_nav_ai_desc', 'en', 'Deep-dive into any stock with our AI agents. Get fundamental, technical, and macro analysis in your language.', 'tour'),
('tour_nav_screener_title', 'en', 'Stock Screener', 'tour'),
('tour_nav_screener_desc', 'en', 'Find actionable buy and sell candidates filtered by our AI scoring system. Updated daily for each market.', 'tour'),
('tour_nav_studio_title', 'en', 'AI Studio', 'tour'),
('tour_nav_studio_desc', 'en', 'Create your own custom AI strategies. Define rules, backtest, and let AI run your analysis automatically.', 'tour'),
('tour_copilot_title', 'en', 'AI Copilot', 'tour'),
('tour_copilot_desc', 'en', 'Your personal AI assistant — always available in the corner. Ask anything about markets, stocks, or your portfolio.', 'tour'),

-- Simplified Chinese (zh)
('tour_step_label', 'zh', '步骤', 'tour'),
('tour_skip', 'zh', '跳过导览', 'tour'),
('tour_back', 'zh', '上一步', 'tour'),
('tour_next', 'zh', '下一步', 'tour'),
('tour_finish', 'zh', '知道了！', 'tour'),
('tour_search_title', 'zh', '搜索任意股票', 'tour'),
('tour_search_desc', 'zh', '输入股票代码或公司名称，直接跳转到分析页面。支持全球9个市场。', 'tour'),
('tour_watchlist_title', 'zh', '添加到自选股', 'tour'),
('tour_watchlist_desc', 'zh', '点击股票卡片上的星标即可关注。自选股跨设备同步，并为AI提供个性化建议。', 'tour'),
('tour_nav_watchlist_title', 'zh', '我的自选股', 'tour'),
('tour_nav_watchlist_desc', 'zh', '所有关注的股票汇集一处。一目了然查看价格、涨跌和AI提醒。', 'tour'),
('tour_nav_ai_title', 'zh', 'AI分析', 'tour'),
('tour_nav_ai_desc', 'zh', '用AI代理深入分析任意股票。获取基本面、技术面和宏观分析，支持您的语言。', 'tour'),
('tour_nav_screener_title', 'zh', '选股器', 'tour'),
('tour_nav_screener_desc', 'zh', '通过AI评分系统筛选出可操作的买卖候选股。每日更新各市场数据。', 'tour'),
('tour_nav_studio_title', 'zh', 'AI工作室', 'tour'),
('tour_nav_studio_desc', 'zh', '创建您的自定义AI策略。定义规则、回测，让AI自动运行分析。', 'tour'),
('tour_copilot_title', 'zh', 'AI助手', 'tour'),
('tour_copilot_desc', 'zh', '您的私人AI助手——随时在角落待命。关于市场、股票或投资组合，尽管提问。', 'tour'),

-- Traditional Chinese (zh-TW)
('tour_step_label', 'zh-TW', '步驟', 'tour'),
('tour_skip', 'zh-TW', '跳過導覽', 'tour'),
('tour_back', 'zh-TW', '上一步', 'tour'),
('tour_next', 'zh-TW', '下一步', 'tour'),
('tour_finish', 'zh-TW', '知道了！', 'tour'),
('tour_search_title', 'zh-TW', '搜尋任意股票', 'tour'),
('tour_search_desc', 'zh-TW', '輸入股票代碼或公司名稱，直接跳轉到分析頁面。支援全球9個市場。', 'tour'),
('tour_watchlist_title', 'zh-TW', '加入自選股', 'tour'),
('tour_watchlist_desc', 'zh-TW', '點擊股票卡片上的星標即可追蹤。自選股跨裝置同步，並為AI提供個人化建議。', 'tour'),
('tour_nav_watchlist_title', 'zh-TW', '我的自選股', 'tour'),
('tour_nav_watchlist_desc', 'zh-TW', '所有追蹤的股票匯集一處。一目了然查看價格、漲跌和AI提醒。', 'tour'),
('tour_nav_ai_title', 'zh-TW', 'AI分析', 'tour'),
('tour_nav_ai_desc', 'zh-TW', '用AI代理深入分析任意股票。取得基本面、技術面和總體分析，支援您的語言。', 'tour'),
('tour_nav_screener_title', 'zh-TW', '選股器', 'tour'),
('tour_nav_screener_desc', 'zh-TW', '透過AI評分系統篩選出可操作的買賣候選股。每日更新各市場數據。', 'tour'),
('tour_nav_studio_title', 'zh-TW', 'AI工作室', 'tour'),
('tour_nav_studio_desc', 'zh-TW', '建立您的自訂AI策略。定義規則、回測，讓AI自動執行分析。', 'tour'),
('tour_copilot_title', 'zh-TW', 'AI助手', 'tour'),
('tour_copilot_desc', 'zh-TW', '您的私人AI助手——隨時在角落待命。關於市場、股票或投資組合，儘管提問。', 'tour'),

-- Japanese (ja)
('tour_step_label', 'ja', 'ステップ', 'tour'),
('tour_skip', 'ja', 'ツアーをスキップ', 'tour'),
('tour_back', 'ja', '戻る', 'tour'),
('tour_next', 'ja', '次へ', 'tour'),
('tour_finish', 'ja', '了解！', 'tour'),
('tour_search_title', 'ja', '銘柄を検索', 'tour'),
('tour_search_desc', 'ja', 'ティッカーまたは会社名を入力して分析ページへ直行。9つの市場すべてに対応。', 'tour'),
('tour_watchlist_title', 'ja', 'ウォッチリストに追加', 'tour'),
('tour_watchlist_desc', 'ja', '銘柄カードの星をクリックして追跡。ウォッチリストはデバイス間で同期し、AIコパイロットに反映されます。', 'tour'),
('tour_nav_watchlist_title', 'ja', 'ウォッチリスト', 'tour'),
('tour_nav_watchlist_desc', 'ja', 'お気に入り銘柄を一覧表示。価格・変動率・AIアラートを一目で確認。', 'tour'),
('tour_nav_ai_title', 'ja', 'AI分析', 'tour'),
('tour_nav_ai_desc', 'ja', 'AIエージェントで銘柄を深掘り分析。ファンダメンタル・テクニカル・マクロ分析をお好みの言語で。', 'tour'),
('tour_nav_screener_title', 'ja', 'スクリーナー', 'tour'),
('tour_nav_screener_desc', 'ja', 'AIスコアリングで厳選した売買候補を表示。各市場毎日更新。', 'tour'),
('tour_nav_studio_title', 'ja', 'AIスタジオ', 'tour'),
('tour_nav_studio_desc', 'ja', 'カスタムAI戦略を作成。ルール定義・バックテスト・自動分析を実現。', 'tour'),
('tour_copilot_title', 'ja', 'AIコパイロット', 'tour'),
('tour_copilot_desc', 'ja', 'あなた専用のAIアシスタント——画面の隅にいつでも待機。市場・銘柄・ポートフォリオ、何でもお聞きください。', 'tour'),

-- Korean (ko)
('tour_step_label', 'ko', '단계', 'tour'),
('tour_skip', 'ko', '투어 건너뛰기', 'tour'),
('tour_back', 'ko', '이전', 'tour'),
('tour_next', 'ko', '다음', 'tour'),
('tour_finish', 'ko', '알겠습니다!', 'tour'),
('tour_search_title', 'ko', '종목 검색', 'tour'),
('tour_search_desc', 'ko', '티커 또는 회사명을 입력하여 분석 페이지로 바로 이동하세요. 9개 시장 모두 지원합니다.', 'tour'),
('tour_watchlist_title', 'ko', '관심 종목에 추가', 'tour'),
('tour_watchlist_desc', 'ko', '종목 카드의 별표를 클릭하여 추적하세요. 관심 종목은 기기 간 동기화되며 AI 코파일럿에 반영됩니다.', 'tour'),
('tour_nav_watchlist_title', 'ko', '관심 종목', 'tour'),
('tour_nav_watchlist_desc', 'ko', '즐겨찾기 종목을 한곳에서 확인. 가격, 변동률, AI 알림을 한눈에 파악.', 'tour'),
('tour_nav_ai_title', 'ko', 'AI 분석', 'tour'),
('tour_nav_ai_desc', 'ko', 'AI 에이전트로 종목을 심층 분석. 기본적, 기술적, 거시 분석을 원하는 언어로 제공.', 'tour'),
('tour_nav_screener_title', 'ko', '종목 스크리너', 'tour'),
('tour_nav_screener_desc', 'ko', 'AI 스코어링으로 선별된 매수/매도 후보 종목 확인. 시장별 매일 업데이트.', 'tour'),
('tour_nav_studio_title', 'ko', 'AI 스튜디오', 'tour'),
('tour_nav_studio_desc', 'ko', '맞춤 AI 전략을 만드세요. 규칙 정의, 백테스트, AI 자동 분석 실행.', 'tour'),
('tour_copilot_title', 'ko', 'AI 코파일럿', 'tour'),
('tour_copilot_desc', 'ko', '개인 AI 어시스턴트 — 화면 모서리에서 항상 대기. 시장, 종목, 포트폴리오에 대해 무엇이든 질문하세요.', 'tour'),

-- Vietnamese (vi)
('tour_step_label', 'vi', 'Bước', 'tour'),
('tour_skip', 'vi', 'Bỏ qua hướng dẫn', 'tour'),
('tour_back', 'vi', 'Quay lại', 'tour'),
('tour_next', 'vi', 'Tiếp theo', 'tour'),
('tour_finish', 'vi', 'Đã hiểu!', 'tour'),
('tour_search_title', 'vi', 'Tìm kiếm cổ phiếu', 'tour'),
('tour_search_desc', 'vi', 'Nhập mã cổ phiếu hoặc tên công ty để chuyển đến trang phân tích. Hỗ trợ tất cả 9 thị trường.', 'tour'),
('tour_watchlist_title', 'vi', 'Thêm vào danh mục theo dõi', 'tour'),
('tour_watchlist_desc', 'vi', 'Nhấn ngôi sao trên thẻ cổ phiếu để theo dõi. Danh mục đồng bộ giữa các thiết bị và cung cấp gợi ý AI cá nhân.', 'tour'),
('tour_nav_watchlist_title', 'vi', 'Danh mục theo dõi', 'tour'),
('tour_nav_watchlist_desc', 'vi', 'Tất cả cổ phiếu yêu thích ở một nơi. Xem giá, biến động và cảnh báo AI trong nháy mắt.', 'tour'),
('tour_nav_ai_title', 'vi', 'Phân tích AI', 'tour'),
('tour_nav_ai_desc', 'vi', 'Phân tích chuyên sâu bất kỳ cổ phiếu nào với AI. Nhận phân tích cơ bản, kỹ thuật và vĩ mô bằng ngôn ngữ của bạn.', 'tour'),
('tour_nav_screener_title', 'vi', 'Bộ lọc cổ phiếu', 'tour'),
('tour_nav_screener_desc', 'vi', 'Tìm cổ phiếu đáng mua bán được AI chấm điểm. Cập nhật hàng ngày cho mỗi thị trường.', 'tour'),
('tour_nav_studio_title', 'vi', 'AI Studio', 'tour'),
('tour_nav_studio_desc', 'vi', 'Tạo chiến lược AI tùy chỉnh. Định nghĩa quy tắc, backtest và để AI tự động phân tích.', 'tour'),
('tour_copilot_title', 'vi', 'AI Copilot', 'tour'),
('tour_copilot_desc', 'vi', 'Trợ lý AI cá nhân — luôn sẵn sàng ở góc màn hình. Hỏi bất cứ điều gì về thị trường, cổ phiếu hoặc danh mục đầu tư.', 'tour'),

-- Thai (th)
('tour_step_label', 'th', 'ขั้นตอน', 'tour'),
('tour_skip', 'th', 'ข้ามทัวร์', 'tour'),
('tour_back', 'th', 'ย้อนกลับ', 'tour'),
('tour_next', 'th', 'ถัดไป', 'tour'),
('tour_finish', 'th', 'เข้าใจแล้ว!', 'tour'),
('tour_search_title', 'th', 'ค้นหาหุ้น', 'tour'),
('tour_search_desc', 'th', 'พิมพ์รหัสหุ้นหรือชื่อบริษัทเพื่อไปยังหน้าวิเคราะห์ รองรับทั้ง 9 ตลาด', 'tour'),
('tour_watchlist_title', 'th', 'เพิ่มในรายการติดตาม', 'tour'),
('tour_watchlist_desc', 'th', 'คลิกดาวบนการ์ดหุ้นเพื่อติดตาม รายการซิงค์ข้ามอุปกรณ์และช่วยให้ AI แนะนำได้ตรงจุด', 'tour'),
('tour_nav_watchlist_title', 'th', 'รายการติดตาม', 'tour'),
('tour_nav_watchlist_desc', 'th', 'หุ้นที่คุณติดตามทั้งหมดในที่เดียว ดูราคา การเปลี่ยนแปลง และการแจ้งเตือน AI ได้ทันที', 'tour'),
('tour_nav_ai_title', 'th', 'วิเคราะห์ AI', 'tour'),
('tour_nav_ai_desc', 'th', 'วิเคราะห์เชิงลึกหุ้นใดก็ได้ด้วย AI รับการวิเคราะห์ปัจจัยพื้นฐาน เทคนิคัล และมหภาคในภาษาของคุณ', 'tour'),
('tour_nav_screener_title', 'th', 'คัดกรองหุ้น', 'tour'),
('tour_nav_screener_desc', 'th', 'ค้นหาหุ้นน่าซื้อขายที่คัดกรองด้วย AI อัปเดตรายวันสำหรับแต่ละตลาด', 'tour'),
('tour_nav_studio_title', 'th', 'AI Studio', 'tour'),
('tour_nav_studio_desc', 'th', 'สร้างกลยุทธ์ AI ที่กำหนดเอง กำหนดกฎ ทดสอบย้อนหลัง และให้ AI วิเคราะห์อัตโนมัติ', 'tour'),
('tour_copilot_title', 'th', 'AI Copilot', 'tour'),
('tour_copilot_desc', 'th', 'ผู้ช่วย AI ส่วนตัว — พร้อมให้บริการที่มุมจอเสมอ ถามอะไรก็ได้เกี่ยวกับตลาด หุ้น หรือพอร์ตของคุณ', 'tour'),

-- Malay (ms)
('tour_step_label', 'ms', 'Langkah', 'tour'),
('tour_skip', 'ms', 'Langkau panduan', 'tour'),
('tour_back', 'ms', 'Kembali', 'tour'),
('tour_next', 'ms', 'Seterusnya', 'tour'),
('tour_finish', 'ms', 'Faham!', 'tour'),
('tour_search_title', 'ms', 'Cari saham', 'tour'),
('tour_search_desc', 'ms', 'Taip kod saham atau nama syarikat untuk terus ke halaman analisis. Menyokong semua 9 pasaran.', 'tour'),
('tour_watchlist_title', 'ms', 'Tambah ke senarai pantau', 'tour'),
('tour_watchlist_desc', 'ms', 'Klik bintang pada kad saham untuk memantau. Senarai pantau disegerakkan merentas peranti dan membantu AI memberi cadangan peribadi.', 'tour'),
('tour_nav_watchlist_title', 'ms', 'Senarai pantau', 'tour'),
('tour_nav_watchlist_desc', 'ms', 'Semua saham kegemaran di satu tempat. Lihat harga, perubahan dan amaran AI dengan pantas.', 'tour'),
('tour_nav_ai_title', 'ms', 'Analisis AI', 'tour'),
('tour_nav_ai_desc', 'ms', 'Analisis mendalam mana-mana saham dengan AI. Dapatkan analisis asas, teknikal dan makro dalam bahasa anda.', 'tour'),
('tour_nav_screener_title', 'ms', 'Penapis Saham', 'tour'),
('tour_nav_screener_desc', 'ms', 'Cari calon beli dan jual yang ditapis oleh sistem pemarkahan AI. Dikemas kini setiap hari untuk setiap pasaran.', 'tour'),
('tour_nav_studio_title', 'ms', 'AI Studio', 'tour'),
('tour_nav_studio_desc', 'ms', 'Cipta strategi AI tersuai. Tentukan peraturan, ujian balik, dan biarkan AI menjalankan analisis secara automatik.', 'tour'),
('tour_copilot_title', 'ms', 'AI Copilot', 'tour'),
('tour_copilot_desc', 'ms', 'Pembantu AI peribadi anda — sentiasa tersedia di sudut skrin. Tanya apa sahaja tentang pasaran, saham atau portfolio anda.', 'tour')
ON CONFLICT (label_key, lang) DO UPDATE SET text = EXCLUDED.text, category = EXCLUDED.category;
