-- Alerts page i18n labels (8 languages)
-- Category: alerts

INSERT INTO datapai.sys_lang_labels (label_key, lang, text, category) VALUES
-- English
('alerts_title', 'en', 'Change Alerts', 'alerts'),
('alerts_watchlist_title', 'en', 'My Watchlist Alerts', 'alerts'),
('alerts_my_watchlist', 'en', 'My Watchlist', 'alerts'),
('alerts_content_only', 'en', 'Content Only', 'alerts'),
('alerts_all_signals', 'en', 'All Signals', 'alerts'),
('alerts_filtered_out', 'en', 'archive & layout filtered out', 'alerts'),
('alerts_with_changes', 'en', 'with changes', 'alerts'),
('alerts_high_conf', 'en', 'high-confidence', 'alerts'),
('alerts_ag2_signals', 'en', 'AG2 signals', 'alerts'),
('alerts_investigated', 'en', '{n} investigated', 'alerts'),
('alerts_legend_moderate', 'en', 'Moderate change', 'alerts'),
('alerts_legend_high_risk', 'en', 'High-risk language', 'alerts'),
('alerts_legend_positive', 'en', 'Positive / more committed', 'alerts'),
('alerts_conf_explain', 'en', 'Confidence = quality of extracted text', 'alerts'),
('alerts_empty', 'en', 'No analyses yet', 'alerts'),
('alerts_empty_desc', 'en', 'Run a scan from the home page to detect company page changes.', 'alerts'),
('alerts_empty_watchlist', 'en', 'No alerts for your watchlist yet', 'alerts'),
('alerts_empty_watchlist_desc', 'en', 'Run a scan from your watchlist page to detect changes on your stocks.', 'alerts'),
('alerts_back_watchlist', 'en', 'Back to Watchlist', 'alerts'),
('alerts_go_home', 'en', 'Go Home', 'alerts'),
('alerts_col_company', 'en', 'Company', 'alerts'),
('alerts_col_score', 'en', 'Score', 'alerts'),
('alerts_col_changed', 'en', 'Changed', 'alerts'),
('alerts_col_conf', 'en', 'Conf.', 'alerts'),
('alerts_col_signal', 'en', 'Signal', 'alerts'),
('alerts_col_validation', 'en', 'Validation', 'alerts'),
('alerts_col_scanned', 'en', 'Scanned', 'alerts'),
('alerts_signal_content_change', 'en', 'Content Change', 'alerts'),
('alerts_signal_archive_change', 'en', 'Archive Change', 'alerts'),
('alerts_signal_layout_change', 'en', 'Layout Change', 'alerts'),
('alerts_type_archive', 'en', 'Archive', 'alerts'),
('alerts_type_layout', 'en', 'Layout', 'alerts'),
('alerts_agent_guidance', 'en', 'Guidance Withdrawal', 'alerts'),
('alerts_agent_risk', 'en', 'Risk Expansion', 'alerts'),
('alerts_agent_tone', 'en', 'Tone Softening', 'alerts'),
('alerts_severity_high', 'en', 'HIGH', 'alerts'),
('alerts_severity_medium', 'en', 'MEDIUM', 'alerts'),
('alerts_severity_low', 'en', 'LOW', 'alerts'),
('alerts_val_confirmed', 'en', 'Confirmed', 'alerts'),
('alerts_val_partial', 'en', 'Partial', 'alerts'),
('alerts_val_unconfirmed', 'en', 'Unconfirmed', 'alerts'),
('alerts_val_no_source', 'en', 'No source', 'alerts'),

-- Simplified Chinese (zh)
('alerts_title', 'zh', '变动警报', 'alerts'),
('alerts_watchlist_title', 'zh', '自选股警报', 'alerts'),
('alerts_my_watchlist', 'zh', '我的自选股', 'alerts'),
('alerts_content_only', 'zh', '仅内容变动', 'alerts'),
('alerts_all_signals', 'zh', '全部信号', 'alerts'),
('alerts_filtered_out', 'zh', '已过滤存档和布局变动', 'alerts'),
('alerts_with_changes', 'zh', '有变动', 'alerts'),
('alerts_high_conf', 'zh', '高置信度', 'alerts'),
('alerts_ag2_signals', 'zh', '个AG2信号', 'alerts'),
('alerts_investigated', 'zh', '{n} 已调查', 'alerts'),
('alerts_legend_moderate', 'zh', '中度变动', 'alerts'),
('alerts_legend_high_risk', 'zh', '高风险措辞', 'alerts'),
('alerts_legend_positive', 'zh', '正面 / 更积极', 'alerts'),
('alerts_conf_explain', 'zh', '置信度 = 提取文本的质量', 'alerts'),
('alerts_empty', 'zh', '暂无分析', 'alerts'),
('alerts_empty_desc', 'zh', '从首页运行扫描以检测公司页面变化。', 'alerts'),
('alerts_empty_watchlist', 'zh', '您的自选股暂无警报', 'alerts'),
('alerts_empty_watchlist_desc', 'zh', '从自选股页面运行扫描以检测股票变化。', 'alerts'),
('alerts_back_watchlist', 'zh', '返回自选股', 'alerts'),
('alerts_go_home', 'zh', '返回首页', 'alerts'),
('alerts_col_company', 'zh', '公司', 'alerts'),
('alerts_col_score', 'zh', '评分', 'alerts'),
('alerts_col_changed', 'zh', '变动', 'alerts'),
('alerts_col_conf', 'zh', '置信度', 'alerts'),
('alerts_col_signal', 'zh', '信号', 'alerts'),
('alerts_col_validation', 'zh', '验证', 'alerts'),
('alerts_col_scanned', 'zh', '扫描时间', 'alerts'),
('alerts_signal_content_change', 'zh', '内容变动', 'alerts'),
('alerts_signal_archive_change', 'zh', '存档变动', 'alerts'),
('alerts_signal_layout_change', 'zh', '布局变动', 'alerts'),
('alerts_type_archive', 'zh', '存档', 'alerts'),
('alerts_type_layout', 'zh', '布局', 'alerts'),
('alerts_agent_guidance', 'zh', '指引撤回', 'alerts'),
('alerts_agent_risk', 'zh', '风险扩大', 'alerts'),
('alerts_agent_tone', 'zh', '语气软化', 'alerts'),
('alerts_severity_high', 'zh', '高', 'alerts'),
('alerts_severity_medium', 'zh', '中', 'alerts'),
('alerts_severity_low', 'zh', '低', 'alerts'),
('alerts_val_confirmed', 'zh', '已确认', 'alerts'),
('alerts_val_partial', 'zh', '部分确认', 'alerts'),
('alerts_val_unconfirmed', 'zh', '未确认', 'alerts'),
('alerts_val_no_source', 'zh', '无来源', 'alerts'),

-- Traditional Chinese (zh-TW)
('alerts_title', 'zh-TW', '變動警報', 'alerts'),
('alerts_watchlist_title', 'zh-TW', '自選股警報', 'alerts'),
('alerts_my_watchlist', 'zh-TW', '我的自選股', 'alerts'),
('alerts_content_only', 'zh-TW', '僅內容變動', 'alerts'),
('alerts_all_signals', 'zh-TW', '全部信號', 'alerts'),
('alerts_filtered_out', 'zh-TW', '已過濾存檔和佈局變動', 'alerts'),
('alerts_with_changes', 'zh-TW', '有變動', 'alerts'),
('alerts_high_conf', 'zh-TW', '高信心度', 'alerts'),
('alerts_ag2_signals', 'zh-TW', '個AG2信號', 'alerts'),
('alerts_investigated', 'zh-TW', '{n} 已調查', 'alerts'),
('alerts_legend_moderate', 'zh-TW', '中度變動', 'alerts'),
('alerts_legend_high_risk', 'zh-TW', '高風險措辭', 'alerts'),
('alerts_legend_positive', 'zh-TW', '正面 / 更積極', 'alerts'),
('alerts_conf_explain', 'zh-TW', '信心度 = 擷取文字的品質', 'alerts'),
('alerts_empty', 'zh-TW', '暫無分析', 'alerts'),
('alerts_empty_desc', 'zh-TW', '從首頁執行掃描以偵測公司頁面變化。', 'alerts'),
('alerts_empty_watchlist', 'zh-TW', '您的自選股暫無警報', 'alerts'),
('alerts_empty_watchlist_desc', 'zh-TW', '從自選股頁面執行掃描以偵測股票變化。', 'alerts'),
('alerts_back_watchlist', 'zh-TW', '返回自選股', 'alerts'),
('alerts_go_home', 'zh-TW', '返回首頁', 'alerts'),
('alerts_col_company', 'zh-TW', '公司', 'alerts'),
('alerts_col_score', 'zh-TW', '評分', 'alerts'),
('alerts_col_changed', 'zh-TW', '變動', 'alerts'),
('alerts_col_conf', 'zh-TW', '信心度', 'alerts'),
('alerts_col_signal', 'zh-TW', '信號', 'alerts'),
('alerts_col_validation', 'zh-TW', '驗證', 'alerts'),
('alerts_col_scanned', 'zh-TW', '掃描時間', 'alerts'),
('alerts_signal_content_change', 'zh-TW', '內容變動', 'alerts'),
('alerts_signal_archive_change', 'zh-TW', '存檔變動', 'alerts'),
('alerts_signal_layout_change', 'zh-TW', '佈局變動', 'alerts'),
('alerts_type_archive', 'zh-TW', '存檔', 'alerts'),
('alerts_type_layout', 'zh-TW', '佈局', 'alerts'),
('alerts_agent_guidance', 'zh-TW', '指引撤回', 'alerts'),
('alerts_agent_risk', 'zh-TW', '風險擴大', 'alerts'),
('alerts_agent_tone', 'zh-TW', '語氣軟化', 'alerts'),
('alerts_severity_high', 'zh-TW', '高', 'alerts'),
('alerts_severity_medium', 'zh-TW', '中', 'alerts'),
('alerts_severity_low', 'zh-TW', '低', 'alerts'),
('alerts_val_confirmed', 'zh-TW', '已確認', 'alerts'),
('alerts_val_partial', 'zh-TW', '部分確認', 'alerts'),
('alerts_val_unconfirmed', 'zh-TW', '未確認', 'alerts'),
('alerts_val_no_source', 'zh-TW', '無來源', 'alerts'),

-- Japanese (ja)
('alerts_title', 'ja', '変動アラート', 'alerts'),
('alerts_watchlist_title', 'ja', 'ウォッチリストのアラート', 'alerts'),
('alerts_my_watchlist', 'ja', 'ウォッチリスト', 'alerts'),
('alerts_content_only', 'ja', 'コンテンツのみ', 'alerts'),
('alerts_all_signals', 'ja', '全シグナル', 'alerts'),
('alerts_filtered_out', 'ja', 'アーカイブ・レイアウト除外済み', 'alerts'),
('alerts_with_changes', 'ja', '件に変動', 'alerts'),
('alerts_high_conf', 'ja', '高信頼度', 'alerts'),
('alerts_ag2_signals', 'ja', 'AG2シグナル', 'alerts'),
('alerts_investigated', 'ja', '{n} 件調査済み', 'alerts'),
('alerts_legend_moderate', 'ja', '中程度の変動', 'alerts'),
('alerts_legend_high_risk', 'ja', '高リスク表現', 'alerts'),
('alerts_legend_positive', 'ja', 'ポジティブ / より確約的', 'alerts'),
('alerts_conf_explain', 'ja', '信頼度 = 抽出テキストの品質', 'alerts'),
('alerts_empty', 'ja', '分析なし', 'alerts'),
('alerts_empty_desc', 'ja', 'ホームページからスキャンを実行して企業ページの変化を検出してください。', 'alerts'),
('alerts_empty_watchlist', 'ja', 'ウォッチリストのアラートはまだありません', 'alerts'),
('alerts_empty_watchlist_desc', 'ja', 'ウォッチリストページからスキャンを実行して変化を検出してください。', 'alerts'),
('alerts_back_watchlist', 'ja', 'ウォッチリストに戻る', 'alerts'),
('alerts_go_home', 'ja', 'ホームへ', 'alerts'),
('alerts_col_company', 'ja', '企業', 'alerts'),
('alerts_col_score', 'ja', 'スコア', 'alerts'),
('alerts_col_changed', 'ja', '変動', 'alerts'),
('alerts_col_conf', 'ja', '信頼度', 'alerts'),
('alerts_col_signal', 'ja', 'シグナル', 'alerts'),
('alerts_col_validation', 'ja', '検証', 'alerts'),
('alerts_col_scanned', 'ja', 'スキャン日時', 'alerts'),
('alerts_signal_content_change', 'ja', 'コンテンツ変動', 'alerts'),
('alerts_signal_archive_change', 'ja', 'アーカイブ変動', 'alerts'),
('alerts_signal_layout_change', 'ja', 'レイアウト変動', 'alerts'),
('alerts_type_archive', 'ja', 'アーカイブ', 'alerts'),
('alerts_type_layout', 'ja', 'レイアウト', 'alerts'),
('alerts_agent_guidance', 'ja', 'ガイダンス撤回', 'alerts'),
('alerts_agent_risk', 'ja', 'リスク拡大', 'alerts'),
('alerts_agent_tone', 'ja', 'トーン軟化', 'alerts'),
('alerts_severity_high', 'ja', '高', 'alerts'),
('alerts_severity_medium', 'ja', '中', 'alerts'),
('alerts_severity_low', 'ja', '低', 'alerts'),
('alerts_val_confirmed', 'ja', '確認済み', 'alerts'),
('alerts_val_partial', 'ja', '一部確認', 'alerts'),
('alerts_val_unconfirmed', 'ja', '未確認', 'alerts'),
('alerts_val_no_source', 'ja', 'ソースなし', 'alerts'),

-- Korean (ko)
('alerts_title', 'ko', '변동 알림', 'alerts'),
('alerts_watchlist_title', 'ko', '관심 종목 알림', 'alerts'),
('alerts_my_watchlist', 'ko', '관심 종목', 'alerts'),
('alerts_content_only', 'ko', '콘텐츠만', 'alerts'),
('alerts_all_signals', 'ko', '전체 신호', 'alerts'),
('alerts_filtered_out', 'ko', '아카이브 및 레이아웃 제외됨', 'alerts'),
('alerts_with_changes', 'ko', '변동 있음', 'alerts'),
('alerts_high_conf', 'ko', '높은 신뢰도', 'alerts'),
('alerts_ag2_signals', 'ko', 'AG2 신호', 'alerts'),
('alerts_investigated', 'ko', '{n}건 조사됨', 'alerts'),
('alerts_legend_moderate', 'ko', '중간 변동', 'alerts'),
('alerts_legend_high_risk', 'ko', '고위험 표현', 'alerts'),
('alerts_legend_positive', 'ko', '긍정적 / 더 확약적', 'alerts'),
('alerts_conf_explain', 'ko', '신뢰도 = 추출 텍스트 품질', 'alerts'),
('alerts_empty', 'ko', '분석 없음', 'alerts'),
('alerts_empty_desc', 'ko', '홈페이지에서 스캔을 실행하여 기업 페이지 변화를 감지하세요.', 'alerts'),
('alerts_empty_watchlist', 'ko', '관심 종목에 알림이 아직 없습니다', 'alerts'),
('alerts_empty_watchlist_desc', 'ko', '관심 종목 페이지에서 스캔을 실행하여 변화를 감지하세요.', 'alerts'),
('alerts_back_watchlist', 'ko', '관심 종목으로 돌아가기', 'alerts'),
('alerts_go_home', 'ko', '홈으로', 'alerts'),
('alerts_col_company', 'ko', '기업', 'alerts'),
('alerts_col_score', 'ko', '점수', 'alerts'),
('alerts_col_changed', 'ko', '변동', 'alerts'),
('alerts_col_conf', 'ko', '신뢰도', 'alerts'),
('alerts_col_signal', 'ko', '신호', 'alerts'),
('alerts_col_validation', 'ko', '검증', 'alerts'),
('alerts_col_scanned', 'ko', '스캔 시간', 'alerts'),
('alerts_signal_content_change', 'ko', '콘텐츠 변동', 'alerts'),
('alerts_signal_archive_change', 'ko', '아카이브 변동', 'alerts'),
('alerts_signal_layout_change', 'ko', '레이아웃 변동', 'alerts'),
('alerts_type_archive', 'ko', '아카이브', 'alerts'),
('alerts_type_layout', 'ko', '레이아웃', 'alerts'),
('alerts_agent_guidance', 'ko', '가이던스 철회', 'alerts'),
('alerts_agent_risk', 'ko', '리스크 확대', 'alerts'),
('alerts_agent_tone', 'ko', '톤 연화', 'alerts'),
('alerts_severity_high', 'ko', '높음', 'alerts'),
('alerts_severity_medium', 'ko', '중간', 'alerts'),
('alerts_severity_low', 'ko', '낮음', 'alerts'),
('alerts_val_confirmed', 'ko', '확인됨', 'alerts'),
('alerts_val_partial', 'ko', '부분 확인', 'alerts'),
('alerts_val_unconfirmed', 'ko', '미확인', 'alerts'),
('alerts_val_no_source', 'ko', '소스 없음', 'alerts'),

-- Vietnamese (vi)
('alerts_title', 'vi', 'Cảnh báo thay đổi', 'alerts'),
('alerts_watchlist_title', 'vi', 'Cảnh báo danh mục theo dõi', 'alerts'),
('alerts_my_watchlist', 'vi', 'Danh mục theo dõi', 'alerts'),
('alerts_content_only', 'vi', 'Chỉ nội dung', 'alerts'),
('alerts_all_signals', 'vi', 'Tất cả tín hiệu', 'alerts'),
('alerts_filtered_out', 'vi', 'đã lọc bỏ lưu trữ & bố cục', 'alerts'),
('alerts_with_changes', 'vi', 'có thay đổi', 'alerts'),
('alerts_high_conf', 'vi', 'độ tin cậy cao', 'alerts'),
('alerts_ag2_signals', 'vi', 'tín hiệu AG2', 'alerts'),
('alerts_investigated', 'vi', '{n} đã điều tra', 'alerts'),
('alerts_legend_moderate', 'vi', 'Thay đổi trung bình', 'alerts'),
('alerts_legend_high_risk', 'vi', 'Ngôn ngữ rủi ro cao', 'alerts'),
('alerts_legend_positive', 'vi', 'Tích cực / cam kết hơn', 'alerts'),
('alerts_conf_explain', 'vi', 'Độ tin cậy = chất lượng văn bản trích xuất', 'alerts'),
('alerts_empty', 'vi', 'Chưa có phân tích', 'alerts'),
('alerts_empty_desc', 'vi', 'Chạy quét từ trang chủ để phát hiện thay đổi trang công ty.', 'alerts'),
('alerts_empty_watchlist', 'vi', 'Chưa có cảnh báo cho danh mục của bạn', 'alerts'),
('alerts_empty_watchlist_desc', 'vi', 'Chạy quét từ trang danh mục để phát hiện thay đổi cổ phiếu.', 'alerts'),
('alerts_back_watchlist', 'vi', 'Quay lại danh mục', 'alerts'),
('alerts_go_home', 'vi', 'Về trang chủ', 'alerts'),
('alerts_col_company', 'vi', 'Công ty', 'alerts'),
('alerts_col_score', 'vi', 'Điểm', 'alerts'),
('alerts_col_changed', 'vi', 'Thay đổi', 'alerts'),
('alerts_col_conf', 'vi', 'Tin cậy', 'alerts'),
('alerts_col_signal', 'vi', 'Tín hiệu', 'alerts'),
('alerts_col_validation', 'vi', 'Xác thực', 'alerts'),
('alerts_col_scanned', 'vi', 'Quét lúc', 'alerts'),
('alerts_signal_content_change', 'vi', 'Thay đổi nội dung', 'alerts'),
('alerts_signal_archive_change', 'vi', 'Thay đổi lưu trữ', 'alerts'),
('alerts_signal_layout_change', 'vi', 'Thay đổi bố cục', 'alerts'),
('alerts_type_archive', 'vi', 'Lưu trữ', 'alerts'),
('alerts_type_layout', 'vi', 'Bố cục', 'alerts'),
('alerts_agent_guidance', 'vi', 'Rút hướng dẫn', 'alerts'),
('alerts_agent_risk', 'vi', 'Mở rộng rủi ro', 'alerts'),
('alerts_agent_tone', 'vi', 'Giọng điệu mềm hơn', 'alerts'),
('alerts_severity_high', 'vi', 'Cao', 'alerts'),
('alerts_severity_medium', 'vi', 'Trung bình', 'alerts'),
('alerts_severity_low', 'vi', 'Thấp', 'alerts'),
('alerts_val_confirmed', 'vi', 'Đã xác nhận', 'alerts'),
('alerts_val_partial', 'vi', 'Một phần', 'alerts'),
('alerts_val_unconfirmed', 'vi', 'Chưa xác nhận', 'alerts'),
('alerts_val_no_source', 'vi', 'Không có nguồn', 'alerts'),

-- Thai (th)
('alerts_title', 'th', 'การแจ้งเตือนการเปลี่ยนแปลง', 'alerts'),
('alerts_watchlist_title', 'th', 'การแจ้งเตือนรายการติดตาม', 'alerts'),
('alerts_my_watchlist', 'th', 'รายการติดตาม', 'alerts'),
('alerts_content_only', 'th', 'เฉพาะเนื้อหา', 'alerts'),
('alerts_all_signals', 'th', 'สัญญาณทั้งหมด', 'alerts'),
('alerts_filtered_out', 'th', 'กรองการเก็บถาวรและเลย์เอาท์ออกแล้ว', 'alerts'),
('alerts_with_changes', 'th', 'มีการเปลี่ยนแปลง', 'alerts'),
('alerts_high_conf', 'th', 'ความเชื่อมั่นสูง', 'alerts'),
('alerts_ag2_signals', 'th', 'สัญญาณ AG2', 'alerts'),
('alerts_investigated', 'th', '{n} รายการถูกตรวจสอบ', 'alerts'),
('alerts_legend_moderate', 'th', 'การเปลี่ยนแปลงปานกลาง', 'alerts'),
('alerts_legend_high_risk', 'th', 'ภาษาเสี่ยงสูง', 'alerts'),
('alerts_legend_positive', 'th', 'เชิงบวก / มุ่งมั่นมากขึ้น', 'alerts'),
('alerts_conf_explain', 'th', 'ความเชื่อมั่น = คุณภาพข้อความที่สกัด', 'alerts'),
('alerts_empty', 'th', 'ยังไม่มีการวิเคราะห์', 'alerts'),
('alerts_empty_desc', 'th', 'เรียกใช้การสแกนจากหน้าแรกเพื่อตรวจจับการเปลี่ยนแปลงหน้าบริษัท', 'alerts'),
('alerts_empty_watchlist', 'th', 'ยังไม่มีการแจ้งเตือนสำหรับรายการของคุณ', 'alerts'),
('alerts_empty_watchlist_desc', 'th', 'เรียกใช้การสแกนจากหน้ารายการติดตามเพื่อตรวจจับการเปลี่ยนแปลง', 'alerts'),
('alerts_back_watchlist', 'th', 'กลับไปรายการติดตาม', 'alerts'),
('alerts_go_home', 'th', 'กลับหน้าแรก', 'alerts'),
('alerts_col_company', 'th', 'บริษัท', 'alerts'),
('alerts_col_score', 'th', 'คะแนน', 'alerts'),
('alerts_col_changed', 'th', 'เปลี่ยนแปลง', 'alerts'),
('alerts_col_conf', 'th', 'ความเชื่อมั่น', 'alerts'),
('alerts_col_signal', 'th', 'สัญญาณ', 'alerts'),
('alerts_col_validation', 'th', 'การตรวจสอบ', 'alerts'),
('alerts_col_scanned', 'th', 'สแกนเมื่อ', 'alerts'),
('alerts_signal_content_change', 'th', 'เนื้อหาเปลี่ยน', 'alerts'),
('alerts_signal_archive_change', 'th', 'เก็บถาวรเปลี่ยน', 'alerts'),
('alerts_signal_layout_change', 'th', 'เลย์เอาท์เปลี่ยน', 'alerts'),
('alerts_type_archive', 'th', 'เก็บถาวร', 'alerts'),
('alerts_type_layout', 'th', 'เลย์เอาท์', 'alerts'),
('alerts_agent_guidance', 'th', 'ถอนแนวทาง', 'alerts'),
('alerts_agent_risk', 'th', 'ขยายความเสี่ยง', 'alerts'),
('alerts_agent_tone', 'th', 'โทนอ่อนลง', 'alerts'),
('alerts_severity_high', 'th', 'สูง', 'alerts'),
('alerts_severity_medium', 'th', 'ปานกลาง', 'alerts'),
('alerts_severity_low', 'th', 'ต่ำ', 'alerts'),
('alerts_val_confirmed', 'th', 'ยืนยันแล้ว', 'alerts'),
('alerts_val_partial', 'th', 'ยืนยันบางส่วน', 'alerts'),
('alerts_val_unconfirmed', 'th', 'ยังไม่ยืนยัน', 'alerts'),
('alerts_val_no_source', 'th', 'ไม่มีแหล่งข้อมูล', 'alerts'),

-- Malay (ms)
('alerts_title', 'ms', 'Amaran Perubahan', 'alerts'),
('alerts_watchlist_title', 'ms', 'Amaran Senarai Pantau', 'alerts'),
('alerts_my_watchlist', 'ms', 'Senarai Pantau', 'alerts'),
('alerts_content_only', 'ms', 'Kandungan Sahaja', 'alerts'),
('alerts_all_signals', 'ms', 'Semua Isyarat', 'alerts'),
('alerts_filtered_out', 'ms', 'arkib & susun atur ditapis', 'alerts'),
('alerts_with_changes', 'ms', 'dengan perubahan', 'alerts'),
('alerts_high_conf', 'ms', 'keyakinan tinggi', 'alerts'),
('alerts_ag2_signals', 'ms', 'isyarat AG2', 'alerts'),
('alerts_investigated', 'ms', '{n} disiasat', 'alerts'),
('alerts_legend_moderate', 'ms', 'Perubahan sederhana', 'alerts'),
('alerts_legend_high_risk', 'ms', 'Bahasa berisiko tinggi', 'alerts'),
('alerts_legend_positive', 'ms', 'Positif / lebih komited', 'alerts'),
('alerts_conf_explain', 'ms', 'Keyakinan = kualiti teks yang diekstrak', 'alerts'),
('alerts_empty', 'ms', 'Belum ada analisis', 'alerts'),
('alerts_empty_desc', 'ms', 'Jalankan imbasan dari halaman utama untuk mengesan perubahan halaman syarikat.', 'alerts'),
('alerts_empty_watchlist', 'ms', 'Belum ada amaran untuk senarai pantau anda', 'alerts'),
('alerts_empty_watchlist_desc', 'ms', 'Jalankan imbasan dari halaman senarai pantau untuk mengesan perubahan saham.', 'alerts'),
('alerts_back_watchlist', 'ms', 'Kembali ke Senarai Pantau', 'alerts'),
('alerts_go_home', 'ms', 'Ke Halaman Utama', 'alerts'),
('alerts_col_company', 'ms', 'Syarikat', 'alerts'),
('alerts_col_score', 'ms', 'Skor', 'alerts'),
('alerts_col_changed', 'ms', 'Berubah', 'alerts'),
('alerts_col_conf', 'ms', 'Keyakinan', 'alerts'),
('alerts_col_signal', 'ms', 'Isyarat', 'alerts'),
('alerts_col_validation', 'ms', 'Pengesahan', 'alerts'),
('alerts_col_scanned', 'ms', 'Diimbas', 'alerts'),
('alerts_signal_content_change', 'ms', 'Perubahan Kandungan', 'alerts'),
('alerts_signal_archive_change', 'ms', 'Perubahan Arkib', 'alerts'),
('alerts_signal_layout_change', 'ms', 'Perubahan Susun Atur', 'alerts'),
('alerts_type_archive', 'ms', 'Arkib', 'alerts'),
('alerts_type_layout', 'ms', 'Susun Atur', 'alerts'),
('alerts_agent_guidance', 'ms', 'Penarikan Panduan', 'alerts'),
('alerts_agent_risk', 'ms', 'Pengembangan Risiko', 'alerts'),
('alerts_agent_tone', 'ms', 'Nada Melemah', 'alerts'),
('alerts_severity_high', 'ms', 'Tinggi', 'alerts'),
('alerts_severity_medium', 'ms', 'Sederhana', 'alerts'),
('alerts_severity_low', 'ms', 'Rendah', 'alerts'),
('alerts_val_confirmed', 'ms', 'Disahkan', 'alerts'),
('alerts_val_partial', 'ms', 'Separa', 'alerts'),
('alerts_val_unconfirmed', 'ms', 'Belum disahkan', 'alerts'),
('alerts_val_no_source', 'ms', 'Tiada sumber', 'alerts')
ON CONFLICT (label_key, lang) DO UPDATE SET text = EXCLUDED.text, category = EXCLUDED.category;
